### ISSUE TITLE
"Failure determining what O...:invoke_void__this___DamageDealer/DamageInfo+3c means"

### ISSUE THREAD

**Issue by dsasmblr** [cheat-engine/cheat-engine#527]
![failure-determining](https://user-images.githubusercontent.com/22781064/52677223-137ae180-2efb-11e9-8d15-ff8cca193934.png)

After dissecting Mono and having the symbol names populate, I was able to NOP the above highlighted instruction. When attempting to right-click to restore original code, that's when the error appeared.

I can close the error and still use CE as normal; however, anywhere I right-click in the disassembler window now results in that error.  Also, attempting to "Restore with original code" in the Advanced Options window is unsuccessful.

**EDIT**: At the prologue of that function, I did use the arrow keys to adjust the offset of the bytes to properly show the disassembled instructions. I'm not sure if that would have created a condition for this error or not. I don't recall if I adjusted those bytes before or after I NOP'ed the instruction that I did.

**Comment by cheat-engine** [comment]
Any chance you where holding CTRL when you nopped that code ?

**Comment by cheat-engine** [comment]
Fixed on Git.  Perhaps I'll make a minor patch later

**Comment by cheat-engine** [comment]
https://github.com/cheat-engine/cheat-engine/releases/download/6.8.3/CheatEngine683.exe

**Comment by dsasmblr** [comment]
Awesome. Thank you, @cheat-engine!

**Comment by dsasmblr** [comment]
Hey, @cheat-engine. Re-opening this as the issue is still present in 6.8.3, but perhaps in a slightly different manner with a saved CT.

![1](https://user-images.githubusercontent.com/22781064/53363738-449bde80-390b-11e9-93f5-daee5917c3f4.png)

After opening a saved CT, that error pops up even if you've not yet activated Mono features. The error condition seems to be if you've made changes to code while Mono features were activated and a reference was saved in the Advanced Options by symbol name:

![2](https://user-images.githubusercontent.com/22781064/53364482-e07a1a00-390c-11e9-947d-2b924c4da194.png)

The result is the same as the original issue: cannot right-click in disassembler. However, if I now activate Mono features, then everything works alright since the reference is then valid.

**Comment by cheat-engine** [comment]
Did you create this table when that bug was present? Because normally it won't add those names as symbols

**Comment by dsasmblr** [comment]
No, this is a table I created brand new. I actually rarely add anything manually to the code list. I've been doing a lot of re-enabling Mono features, though. So, for instance, I'll find my way into a subroutine with Mono features activated. Then I use break/trace with step-over to find my way to the caller and nop the call instruction there.

With this game, I've been working in a varied state of re-enabling Mono features after break/trace, sometimes before I modify an instruction like the call I mentioned in the scenario above. I'd try some things specifically right now but I'm at work. Just not sure if that workflow is of any consequence to the scenario, etc.

**Comment by cheat-engine** [comment]
should be fixed
